<h2 style='color:darkgreen'> Basic mathematical functions in numPy</h2>


In [2]:
# import numPy package and alias as np

import numpy as np

In [2]:
# array addition

# create an array x and y and perform addtion / sum 

x = np.array([[1, 2, 3],[1, 2, 3]])

y = np.array([1, 1, 1])

z = x + y                                                         # elementwise addition

print(' ')

print(z)                                                          # prints [[2 3 4]
                                                                  #          [2 3 4]]

print("\n Add function to find sum of two array\n")

print(np.add(x ,y ))                                              # prints [[2 3 4]
                                                                  #          [2 3 4]]   same as  operator '+'

 
[[2 3 4]
 [2 3 4]]

 Add function to find sum of two array

[[2 3 4]
 [2 3 4]]


In [3]:
# array subtraction

# create an array x and y and perform subtraction / difference

x = np.array([[1, 2, 3], [1, 2, 3]])

y = np.array([[1, 2, 3], [1, 2, 3]])

z = x - y                                                         # elementwise subtraction

print(' ')

print(z)                                                          # prints    [[0 0 0]
                                                                  #            [0 0 0]]


print("\n subtract function to find difference of two array\n")

print(np.subtract(x ,y ))                                              # prints [[0 0 0]
                                                                  #             [0 0 0]] same as operator '-'

 
[[0 0 0]
 [0 0 0]]

 subtract function to find difference of two array

[[0 0 0]
 [0 0 0]]


In [4]:
# array multiplication

# NOTE that its not matrix multiplication
 
# create an array x and y and perform multiplication / product


x = np.array([[1, 2, 3], [1, 2, 3]])

y = np.array([[2, 2, 2], [1, 1, 1]])

z = x * y

print(' ')

print(z)                                                          # prints    [[2 4 6]
                                                                  #            [1 2 3]]

print("\n multiply function to find product of two array\n")

print(np.multiply(x ,y ))                                         # performs elementwise multiplication
                                                                
                                                                  # prints    [[2 4 6]
                                                                  #            [1 2 3]]  same as operator '-'

 
[[2 4 6]
 [1 2 3]]

 multiply function to find product of two array

[[2 4 6]
 [1 2 3]]


In [5]:
# array division

x = np.array([[1, 2, 3], [1, 2, 3]])

y = np.array([[1, 1, 1], [1, 2, 3]])

z = x / y                                                         # elementwise division

print(' ')

print(z)                                                          # prints   [[1. 2. 3.]
                                                                  #           [1. 1. 1.]]


print("\n divide function to perform division of two array\n")

print(np.divide(x ,y ))                                              # prints   [[1. 2. 3.]
                                                                  #              [1. 1. 1.]] same as operator '/'

 
[[1. 2. 3.]
 [1. 1. 1.]]

 divide function to perform division of two array

[[1. 2. 3.]
 [1. 1. 1.]]


In [6]:
# find square root
import numpy as np

x = np.array([[4 ,25 ], [16 ,36]])                               # creates an np array 
print(' ')
print(np.sqrt(x))                                                # perform element-wise operation
                                                                 

 
[[2. 5.]
 [4. 6.]]


Changing the Shape of an array


In [9]:
# function to reshape an array
# create a 1D array

x = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ])                           
print(' ')
print(x)                                                          # prints [1 2 3 4 5 6 7 8]
 
y = x.reshape(2 ,4)                                               # reshape array into 2 * 4 
print(' ')
print(y)

 
[1 2 3 4 5 6 7 8]
 
[[1 2 3 4]
 [5 6 7 8]]


In [22]:
# flatten an array

print(' ')

y.flatten()                                                         # reshape array into single dimension 

array([1, 2, 3, 1, 2, 3])

In [21]:
# ravel function to flatten an array


x = np.array([[1, 2, 3], [1, 2, 3]])

print(' ')

print(x.shape)

y = x.ravel()

print(' ')

print(y)

print(' ')

print(y.shape)

 
(2, 3)
 
[1 2 3 1 2 3]
 
(6,)


**Mathematical Functions for matrix** 

In [40]:
# matrix multiplication

mat1 = np.matrix([[1 ,2 ,3] ,[2 ,4 ,1], [3 ,5 ,3]])

mat2 = np.matrix([[1 ,2 ,2] ,[2 ,4 ,1], [1 ,1 ,1]])

prod1 = np.matmul(mat1 ,mat2)                                     # both matmul and dot performs matrix 
                                                                      
prod2 = mat1.dot(mat2)                                            # multiplication but with different broadcasting
                                                                      
print(prod1)                                                                 # rules

print(' ')

print(prod2)

print(' ')



[[ 8 13  7]
 [11 21  9]
 [16 29 14]]
 
[[ 8 13  7]
 [11 21  9]
 [16 29 14]]
 


In [32]:
# inverse of a matrix

mat3 = np.matrix([[1 ,4 ,3] ,[2 ,2 ,1], [7 ,5 ,9]])

print(np.linalg.inv(mat3))

[[-0.30232558  0.48837209  0.04651163]
 [ 0.25581395  0.27906977 -0.11627907]
 [ 0.09302326 -0.53488372  0.13953488]]


In [39]:
# transpose of a matrix

trans = np.transpose(mat3)

print(trans)

print(' ')

print(mat3.T)

[[1 2 7]
 [4 2 5]
 [3 1 9]]
[[1 2 7]
 [4 2 5]
 [3 1 9]]


**Joining and Stacking Arrays**

1. concatenate
2. stack
3. hstack
4. vstack

In [46]:
# perform concatenate and stacking two arrays 

# if we do not specify axis , by default it is 0

arr1 = np.array([[1 ,2 ,3]  ,[4 ,5 ,6] ,[7 ,8 ,9]])

arr2 = np.array([[1 ,1 ,1] ,[2 ,2 ,2] ,[3 ,3 ,3]])

# concatenate function

print('\n concatenate along axis 0: \n')

arr_conc0 = np.concatenate((arr1 ,arr2) ,axis = 0 )                 # concatenates array along rows i. e axis 0  

print(arr_conc0)

print('\n concatenate along axis 1 :\n')

arr_conc1 = np.concatenate((arr1 ,arr2) ,axis = 1 )                 # concatenates array along columns i. e axis 0  

print(arr_conc1)







 concatenate along axis 0: 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]
 [2 2 2]
 [3 3 3]]

 concatenate along axis 1 :

[[1 2 3 1 1 1]
 [4 5 6 2 2 2]
 [7 8 9 3 3 3]]


In [47]:
# stacking is same as concatenation , only difference is it is done along a new axis.

print('\n stack along axis 0: \n')

arr_sta0 = np.stack((arr1 ,arr2) ,axis = 0 )                        

print(arr_sta0)

print('\n stack along axis 1: \n')

arr_sta1 = np.stack((arr1 ,arr2) ,axis = 1 )

print(arr_sta1)


 stack along axis 0: 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]

 stack along axis 1: 

[[[1 2 3]
  [1 1 1]]

 [[4 5 6]
  [2 2 2]]

 [[7 8 9]
  [3 3 3]]]


In [48]:
# vertical and horizontal stacking

arr_vsta = np.vstack((arr1 ,arr2))

print('\n vertical stacking : \n')

print(arr_vsta)

print('\n horizontally stacking : \n')

arr_hsta = np.hstack((arr1 ,arr2))

print(arr_hsta)


 vertical stacking : 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 1 1]
 [2 2 2]
 [3 3 3]]

 horizontally stacking : 

[[1 2 3 1 1 1]
 [4 5 6 2 2 2]
 [7 8 9 3 3 3]]


In [4]:
# Sorting

arr_sort = np.array([3 , 5 ,2, 1 ,4])
print(np.sort(arr_sort))


[1 2 3 4 5]


In [6]:
# Trignometric funtions 
# print sine , cosine , tan of the array

arr_fun = np.array([1 , 2 , 3])
print('Sine of array:\n', np.sin(arr_fun))
print('\n cosine of array:\n',np.cos(arr_fun))



Sine of array:
 [0.84147098 0.90929743 0.14112001]

 cosine of array:
 [ 0.54030231 -0.41614684 -0.9899925 ]


In [8]:
# Linear algebra functions

# rank of matrix
mat_algebra = np.array([[1 , 2 ,3],[4 , 5, 6],[7 , 8 ,9]])
print('Rank of the matrix:\n',np.linalg.matrix_rank(mat_algebra) )

# determinant of matrix
print('Determinant of the matrix:\n',np.linalg.det(mat_algebra) )

# Inverse of a matrix
print('Inverse of the matrix:\n',np.linalg.inv(mat_algebra) )

# find eigen value and eigen vector
print('Eigen values of the matrix:\n',np.linalg.eigvals(mat_algebra) )

Rank of the matrix:
 2
Determinant of the matrix:
 -9.51619735392994e-16
Inverse of the matrix:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Eigen values of the matrix:
 [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
